Added missing UTF-8 enconding to open
```
Traceback (most recent call last):
  File "check-po-files.py", line 108, in <module>
    problems += fix_po(path)
  File "check-po-files.py", line 52, in fix_po
    for line in open(path):
  File "F:\Python\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 726: character maps to <undefined>
make[1]: *** [Makefile:33: .build/i18n] Error 1
```